project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "data/*.csv"
    - "data/"

website:
  title: "Jaden Chant"
  navbar:
    background: "#2e3f58"
    left:
      - href: index.qmd
        text: Home
      - pages/about.qmd
      - pages/projects.qmd
      - sidebar:maps

  sidebar:
    - id: maps
      title: "Maps"
      contents:
        - file: pages/maps/us_states.qmd
          text: "US States"
        - file: pages/maps/wisconsin_districs.qmd
          text: "Wisconsin Districts"

format:
  bookup-html:
    theme: bookup-html+darkonly

editor: source

