project:
  type: website
  output-dir: docs

website:
  title: "Jaden Chant"
  navbar:
    background: "#2e3f58"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  bookup-html:
    theme: bookup-html+darkonly
    toc: true
    toc-depth: 3

editor: source

