project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "data/*.csv"
    - "data/"

website:
  title: "Jaden Chant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/projects.qmd
        text: Projects
      - sidebar:miniproj

  sidebar:
    - id: miniproj
      title: "Mini Projects"
      contents:
        - section: "Maps"
          contents:
          - href: pages/maps/us_states.qmd
            text: "US States"
          - href: pages/maps/wisconsin_districs.qmd
            text: "Wisconsin Districts"
        - href: pages/simulation.qmd
          text: Simulation
        - href: pages/str.qmd
          text: RegEx

  page-footer: 
    left: "Jaden Chant"
    right: 
      - icon: github
        href: https://github.com/jadenchant/jadenchant.github.io


format:
  html:
    theme: cyborg

editor: source

