project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "data/*.csv"
    - "data/"

website:
  title: "Jaden Chant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/projects.qmd
        text: Projects
      - sidebar:miniprojnav

  sidebar:
    - id: miniprojnav
      title: "Mini Projects"
      contents:
        - href: pages/maps/us_states.qmd
          text: "Maps"
        - href: pages/simulation.qmd
          text: "Simulation"
        - href: pages/str.qmd
          text: "RegEx"
    - id: miniproj
      contents:
        - section: "Maps"
          contents:
          - href: pages/maps/us_states.qmd
            text: "US States"
          - href: pages/maps/wisconsin_districs.qmd
            text: "Wisconsin Districts"
        - href: pages/simulation.qmd
          text: "Simulation"
        - href: pages/str.qmd
          text: "RegEx"

  page-footer: 
    center:
      - text: "Jaden Chant"
      - icon: github
        href: https://github.com/jadenchant/jadenchant.github.io

format:
  html:
    theme: cyborg

editor: source
