project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "data/*.csv"
    - "data/"

website:
  title: "Jaden Chant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pages/projects.qmd
        text: Projects
      - sidebar:miniproj
      - sidebar:maps

  sidebar:
    - id: miniproj
      title: "Mini Projects"
      contents:
        - sidebar:maps
        - href: pages/simulation.qmd
          text: Simulation
        - href: pages/str.qmd
          text: RegEx

  sidebar:
    - id: maps
      title: "Maps"
      contents:
        - file: pages/maps/us_states.qmd
          text: "US States"
        - file: pages/maps/wisconsin_districs.qmd
          text: "Wisconsin Districts"

format:
  html:
    theme: cyborg

editor: source

