project:
  type: website
  output-dir: docs

website:
  title: "Jaden Chant"
  navbar:
    background: "#2e3f58"
    left:
      - href: index.qmd
        text: Home
      - pages/about.qmd
      - pages/projects.qmd
      - sidebar:maps

  sidebar:
  - id: maps
      title: "Maps"
      contents:
        - file: pages/maps/us_states.qmd
          text: "US States"
        - file: pages/maps/wisconsin_districs.qmd
          text: "Wisconsin Districts"

format:
  bookup-html:
    theme: bookup-html+darkonly
    toc: true
    toc-depth: 3

editor: source

