---
title: "Simulation"
editor_options: 
  chunk_output_type: console
---


```{r}
#| include: false

library(tidyverse)
library(ggdark)
```


##Airbnb Data
```{r}
airbnb_raw <- read_csv("https://jadenchant.github.io/data/airbnb.csv")

airbnb <- airbnb_raw |>
  filter(reviews > 10) |>
  filter(price < 300) |>
  filter(district %in% c("Southwest", "North", "Northwest", "Central")) |>
  mutate(district = as.factor(district)) |>
  select(price, bedrooms, accommodates, district)
```


```{r}
ggplot(airbnb, aes(x = price, y = bedrooms, color = district)) +
  geom_point() +
  labs(
    title = "Airbnb Prices by Bedrooms",
    x = "Price",
    y = "Bedrooms",
    color = "District"
  ) +
  dark_theme_gray(base_size = 12)

ggplot(airbnb, aes(x = price, y = accommodates, color = district)) +
  geom_point() +
  labs(
    title = "Airbnb Prices by Accommodates",
    x = "Price",
    y = "Accommodates",
    color = "District"
  ) +
  dark_theme_gray(base_size = 12)

ggplot(airbnb, aes(x = district, y = price, fill = district)) +
  geom_boxplot() +
  labs(
    title = "Airbnb Prices by District",
    x = "District",
    y = "Price",
    fill = "District"
  ) +
  dark_theme_gray(base_size = 12)
```

Simulated data, then can you pick the real data out of a crowd



```{r}
gen_prices <- function(true_mean, true_sd, districts, num_in_district, id = 1) {
  table <- tibble(
    district = factor(),
    price = numeric(),
    id = character()
  )

  for (i in 1:length(districts)) {
    sample <- rnorm(num_in_district$n[i], mean = true_mean, sd = true_sd)
    table <- bind_rows(table, tibble(district = rep(districts[i], num_in_district$n[i]), price = sample, id = rep(id, num_in_district$n[i])))
  }

  return(table)
}
```


##Defining Parameters
```{r}
price_mean <- mean(airbnb$price)
price_se <- sd(airbnb$price) / sqrt(length((airbnb$price)))
price_sd <- sd(airbnb$price)

num_in_district <- airbnb |>
  group_by(district) |>
  summarize(n = n())

mean_num_in_district <- mean(num_in_district$n)
```

##Simulating Data
```{r}
#| warning: false

n_sims <- 8
params <- tibble(
  sd = c(rep(price_sd, n_sims)),
  id = c(paste("Sample", 1:n_sims))
)
params

simulation <- params %>%
  pmap_dfr(~ gen_prices(true_mean = price_mean, true_sd = ..1, districts = c("Southwest", "North", "Northwest", "Central"), num_in_district = num_in_district, id = ..2))

airbnb_format <- airbnb |>
  mutate(id = "Truth") |>
  select(district, price, id)

final_sim <- rbind(simulation, airbnb_format)

ggplot(final_sim, aes(x = district, y = price, fill = district)) +
  geom_boxplot() +
  labs(
    title = "Simulated Prices by District",
    x = "District",
    y = "Price",
    fill = "District"
  ) +
  scale_y_continuous(limits = c(0, max(final_sim$price) + 100)) +
  dark_theme_gray(base_size = 12) +
  facet_wrap(~id)
```
