---
title: "US States"
format: 
  bookup-html+darkonly:
    embed-fonts: true
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: false

library(tidyverse)
library(mdsr)
library(maps)
library(viridis)
library(poliscidata)

# cancer_data <- read_csv("https://jadenchant.github.io/data/us_cancer_death.csv")
# 
# cancer_data <- cancer_data |>
#   mutate(state = gsub('.*,\\s*', '', County)) |>
#   mutate(state = str_squish(str_to_lower(as.character(state)))) |>
#   mutate(state = gsub(" ", "", state)) |>
#   mutate(state = gsub("districtofcolumbia[(]state[)]", "districtofcolumbia", state)) |>
#   mutate(state = gsub("<sup>3</sup>", "", state)) |>
#   mutate(avg_death = `Average Deaths per Year`) |>
#   filter(state != "unitedstates") |>
#   filter(!is.na(avg_death)) |>
#   mutate(avg_death = as.numeric(avg_death))
# 
# cancer <- cancer_data |>
#   group_by(state) |>
#   summarise(cancer_death = sum(avg_death))


state_data <- as_tibble(poliscidata::states) |>
  mutate(state_name = str_squish(str_to_lower(as.character(state)))) |>
  select(-state)

us_states <- map_data("state") |>
  mutate(region = str_squish(str_to_lower(as.character(region)))) |>
  mutate(region = gsub(" ", "", region))

 
# state_data |>
#   right_join(us_states, by = c("state_name" = "region")) |>
#   ggplot(mapping = aes(x = long, y = lat,
#                           group = group)) + 
#   geom_polygon(aes(fill = prolife), color = "black") + 
#   labs(fill = "Percent Pro-Life") +
#   coord_map() +
#   theme_void() +
#   scale_fill_viridis(option = "C")
```


```{r}
#| message: false
#| warning: false

# poverty_data <- read_csv("https://jadenchant.github.io/data/poverty_estimates.csv")



```




```{r}
#| message: false
#| warning: false

state_data |>
  right_join(us_states, by = c("state_name" = "region")) |>
  ggplot(mapping = aes(x = long, y = lat,
                          group = group)) + 
  geom_polygon(aes(fill = prolife), color = "black") + 
  labs(fill = "Percent Pro-Life") +
  coord_map() +
  theme_void() +
  scale_fill_viridis(option = "C")
```
