on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install libudunits2
        run: sudo apt-get install -y libudunits2-dev

      - name: update
        run: sudo apt-get update

      - name: Install libproj
        run: sudo apt-get install -y libproj-dev

      - name: Install libgdal
        run: |
          sudo sudo apt update
          sudo apt install libpq-dev gdal-bin libgdal-dev

      - name: Install libfftw3
        run: sudo apt-get install -y libfftw3-dev

      - name: Install libfont
        run: sudo apt-get install libfontconfig1-dev libfreetype6-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: install R packages
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
